export default  {
    "FUNCTIONAPP_ROOT": process.env.FUNCTIONAPP_ROOT,
    "SERVICEBUS_CONN": process.env.SERVICEBUS_CONN,
    "APPINSIGHTS_KEY": process.env.APPINSIGHTS_KEY,
    "BLOBSTORAGE_URI": process.env.BLOBSTORAGE_URI,
    "ENVIRONMENT_PARTITION_KEY" : process.env.ENVIRONMENT_PARTITION_KEY
};