trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - src/.version

pool:
  vmImage: 'windows-latest'

steps:

  - pwsh: |
      & $Env:BUILD_SOURCESDIRECTORY\src\posh-bootstrap.ps1 \n
      $cmd = 'Run -PackAndPublish `
      -nugetApiKey "$(nuget-key)" `
      -azureDevopsPat "$(ado-pat)" `
      -azureWebJobsServiceBus "$(azure-webjobs-servicebus)" `
      -azLoginCmd ''$(az-login)'''
      Write-Host $cmd
      iex $cmd
    displayName: 'Pack and Publish'
    