#should not require modification by developers

trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - src/.version

pool:
  vmImage: 'windows-latest'

steps:
    # the following variables should be setup in the pipeline UI by an administrator
    # nuget-key / used to push class library pkgs / optional may not have any class libraries in solution
    # ado-pat / passed to functionapp to read config from git / optional may not have any functionapps in solution 
    # az-clientid / used to auth azure infrastructure changes via az CLI when deploying az functionapps / optional may not have any function apps in solution 
    # az-clientsecret / used to auth azure infrastructure changes via az CLI when deploying az functionapps / optional may not have any function apps in solution 
    # az-tenantid / used to auth azure infrastructure changes via az CLI when deploying az functionapps / optional may not have any function apps in solution 

  - pwsh: |
      & $Env:BUILD_SOURCESDIRECTORY\src\pwsh-bootstrap.ps1 \n
      $cmd = 'Run -PackAndPublish `
      -nugetApiKey "$(nuget-key)" `
      -azureDevopsPat "$(ado-pat)" `
      -azClientId "$(az-clientid)" `
      -azClientSecret "$(az-clientsecret)" `
      -azTenantId "$(az-tenantid)"'
      Write-Host $cmd
      iex $cmd
    displayName: 'Pack and Publish'
    
  - checkhealth: |
      $result = Invoke-WebRequest "$(vnext-functionappurl)" | Select-Object -ExpandProperty Content
      $result  -match '\+\r\n$'
      if ($result -eq $false) { throw "Health Check Failed" }
    displayName: 'Health Check'
