#should not require modification by developers

trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - src/.version

pool:
  vmImage: 'windows-latest'

steps:
    # the following variables should be setup in the pipeline UI by an administrator
    # nuget-key / used to push class library pkgs / optional may not have any class libraries in solution
    # ado-pat / passed to functionapp to read config from git / optional may not have any functionapps in solution 
    # az-login / used to auth azure infrastructure changes via az CLI when deploying az functionapps / optional may not have any function apps in solution 

  - pwsh: |
      & $Env:BUILD_SOURCESDIRECTORY\src\pwsh-bootstrap.ps1 \n
      $cmd = 'Run -PackAndPublish `
      -nugetApiKey "$(nuget-key)" `
      -azureDevopsPat "$(ado-pat)" `
      -azLoginCmd ''$(az-login)'''
      Write-Host $cmd
      iex $cmd
    displayName: 'Pack and Publish'
    